---
Name: productcomparison
---
SilverShop\Page\Product:
  extensions:
    - 'SilverShop\Comparison\Extension\ProductFeaturesExtension'
SilverShop\Page\ProductController:
  extensions:
    - 'SilverShop\Comparison\Extension\ProductControllerFeaturesExtension'
SilverShop\Admin\ProductCatalogAdmin:
  managed_models:
    - 'SilverShop\Comparison\Model\Feature'
    - 'SilverShop\Comparison\Model\FeatureGroup'
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silvershop/comparison:javascript/shop_comparison_admin.js'
